[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20.12.0"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
