[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "14"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
